package com.snehal.sso.events;

public enum EventType {USER_REGISTERED, USER_LOGGED_IN, LOGIN_FAILED, PASSWORD_RESET_REQUESTED, EMAIL_VERIFIED, ROLE_UPDATED, MFA_ENABLED, MFA_VERIFIED, ACCOUNT_LOCKED, PROFILE_UPDATED}
